project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!files/"
    - "files/functions.qmd"
    - "files/dshs.qmd"

  resources:
    - "*.json"
    - "files"
    - "_extensions"
    - "!lectures/cifar-100-binary/"
    - "!lectures/mnist/"


execute:
  freeze: auto


website:
  repo-url: https://github.com/inqs909/m453_s26
  title: "MATH 453"
  site-url: www.inqs.info/m453_s26
  navbar:
    right:
      - syllabus.qmd
      - hw.qmd
      - ec.qmd
      - books.qmd


format:
  html:
    theme: flatly
    css: styles.css
    toc: true



